version: '3.7'

services:

  aaa:
    image: "${PROJECT_NAME}_aaa:${IMAGE_TAG}"
    build:
      context: ./docker/aaa
      dockerfile: Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION}
        BUILD_HASH: ${BUILD_HASH}
      target: release

  bbb:
    image: "${PROJECT_NAME}_bbb:${IMAGE_TAG}"
    build:
      context: ./
      dockerfile: docker/bbb/Dockerfile
      args:
        BUILD_VERSION: ${BUILD_VERSION}
        BUILD_HASH: ${BUILD_HASH}
      target: release
